# command line: main.py recognition -c/home/f1y/cyh/Neurocomputing2019/config/SBU/train_3A.yaml

base_lr: 0.005
batch_size: 64
config: /home/f1y/cyh/Neurocomputing2019/config/SBU/train_3A.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: network.st_gcn_3A.Model
model_args:
    channel_base: 32
    dropout: 0.5
    edge_importance_weighting: false
    graph_args:
        layout: sbu_edge_2
        strategy: spatial
    graph_args_k:
        layout: sbu_edge_2r
        strategy: spatial
    in_channels: 3
    num_class: 8
    t_length: 100
    temporal_kernel: 5
nesterov: true
num_epoch: 2600
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 5
save_log: true
save_result: false
show_topk:
- 1
start_epoch: 0
step:
- 1500
- 2000
test_batch_size: 64
test_feeder_args:
    data_path: ./data/SBU/val_data_set1.npy
    label_path: ./data/SBU/val_label_set1.pkl
train_feeder_args:
    data_path: ./data/SBU/train_data_set1.npy
    label_path: ./data/SBU/train_label_set1.pkl
use_gpu: true
weight_decay: 0.05
weights: null
work_dir: ./work_dir/SBU/3A_set1
