work_dir: ./work_dir/fusion

joint_weights: /home/f1y/cyh/st-gcn-3A/models/NTU_joint/3A_cs_92.70.pt
part_weights: /home/f1y/cyh/st-gcn-3A/models/NTU_part/3A_cs_92.44.pt

# feeder
feeder: feeder.feeder_fusion.Feeder
test_feeder_args:
  joint_data_path: /home/f1y/cyh/st-gcn-3A/data/NTU_2p_data/xsub/val_data_2per_relation.npy
  part_data_path: /home/f1y/cyh/st-gcn-3A/data/NTU_2p_part/xsub/xsub_val_2pr.npy
  label_path: /home/f1y/cyh/st-gcn-3A/data/NTU_2p_data/xsub/val_label_2per.pkl


# model
joint_model: network.st_gcn_3A.Model
joint_model_args:
  in_channels: 3
  num_class: 11
  dataset: NTU
  temporal_kernel: 9
  channel_base: 64
  edge_importance_weighting: ture
  graph_args:
    layout: 'ntu_edge_2'
    strategy: 'spatial'
  graph_args_k:
    layout: 'ntu_edge_2r'
    strategy: 'spatial'


#part model
part_model: network.st_gcn_3A.Model
part_model_args:
  in_channels: 9
  num_class: 11
  dataset: NTU
  temporal_kernel: 9
  channel_base: 64
  edge_importance_weighting: ture
  graph_args:
    layout: 'ntu_part_2'
    strategy: 'spatial'
  graph_args_k:
    layout: 'ntu_part_2r'
    strategy: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 32
