work_dir: ./work_dir/test
# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU_2p_data/xsub/val_data_2per_relation.npy
  label_path: ./data/NTU_2p_data/xsub/val_label_2per.pkl

#test video 63
#train video 205



# model
#layout: 'openpose'-18 joints, 'ntu-rgb+d'-25 joints
model: network.st_gcn_3A.Model
model_args:
  in_channels: 3
  num_class: 11
  dataset: NTU
  temporal_kernel: 9
  channel_base: 64
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu_edge_2'
    strategy: 'spatial'
  graph_args_k:
    layout: 'ntu_edge_2r'
    strategy: 'spatial'



# test
phase: test
device: [0]
test_batch_size: 32
weights: ./models/NTU_joint/3A_cs_92.70.pt
