work_dir: ./work_dir/SBU/fusion

joint_weights: ./models/SBU_joint/set1_3A_model.pt
part_weights: ./models/SBU_part/set1_3A_model.pt

# feeder
feeder: feeder.feeder_fusion.Feeder
test_feeder_args:
  joint_data_path: ./data/SBU/set1_val_data.npy
  part_data_path: ./data/SBU/set1_val_data_part.npy
  label_path: ./data/SBU/set1_val_label.pkl


# model
joint_model: network.st_gcn_3A.Model
joint_model_args:
  in_channels: 3
  num_class: 8
  t_length: 100
  temporal_kernel: 5
  channel_base: 32
  edge_importance_weighting: True
  graph_args:
    layout: 'sbu_edge_2'
    strategy: 'spatial'
  graph_args_k:
    layout: 'sbu_edge_2r'
    strategy: 'spatial'


#part model
part_model: network.st_gcn_3A.Model
part_model_args:
  in_channels: 9
  num_class: 8
  t_length: 100
  temporal_kernel: 5
  channel_base: 32
  edge_importance_weighting: True
  graph_args:
    layout: 'sbu_part_2'
    strategy: 'spatial'
    graph_args_k:
      layout: 'sbu_part_2r'
      strategy: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 32
