work_dir: ./work_dir/test

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/SBU_2p/val_data_set1.npy
  label_path: ./data/SBU_2p/val_label_set1.pkl


# model
model: network.st_gcn_3A.Model
model_args:
  in_channels: 3
  num_class: 8
  dataset: SBU
  temporal_kernel: 5
  channel_base: 32
  dropout: 0.5
  edge_importance_weighting: False
  graph_args:
    layout: 'sbu_edge_2'
    strategy: 'spatial'
  graph_args_k:
    layout: 'sbu_edge_2r'
    strategy: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 64
weights: ./models/SBU_joint/set1_98.18.pt
