work_dir: ./work_dir/SBU/3A_set1


# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/SBU/train_data_set1.npy
  label_path: ./data/SBU/train_label_set1.pkl
test_feeder_args:
  data_path: ./data/SBU/val_data_set1.npy
  label_path: ./data/SBU/val_label_set1.pkl

# model
model: network.st_gcn_3A.Model
model_args:
  in_channels: 3
  num_class: 8
  dataset: SBU
  temporal_kernel: 5
  channel_base: 32
  dropout: 0.5
  edge_importance_weighting: False
  graph_args:
    layout: 'sbu_edge_2'
    strategy: 'spatial'
  graph_args_k:
    layout: 'sbu_edge_2r'
    strategy: 'spatial'


#optim5
weight_decay: 0.05
base_lr: 0.005
step: [1500, 2000]

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 2600



